<a href="https://colab.research.google.com/github/goelshreya3001-droid/Academic-Project/blob/main/NUMPY_EXERCISE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

**Valid Sudoko**

In [4]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [5]:
np.sum(s,axis=0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [6]:
np.sum(s,axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [7]:
slice=s[0:3,0:3]
slice

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [8]:
slice.sum()

np.int64(45)

In [9]:
slice1=s[0:3,3:6]
slice1

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [10]:
slice2=s[0:3,6:]
slice2

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

Generalize it using loop

In [11]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n=s[i:i+3,j:j+3]
    print(n)
    print(n.sum())

[[5 3 4]
 [6 7 2]
 [1 9 8]]
45
[[6 7 8]
 [1 9 5]
 [3 4 2]]
45
[[9 1 2]
 [3 4 8]
 [5 6 7]]
45
[[8 5 9]
 [4 2 6]
 [7 1 3]]
45
[[7 6 1]
 [8 5 3]
 [9 2 4]]
45
[[4 2 3]
 [7 9 1]
 [8 5 6]]
45
[[9 6 1]
 [2 8 7]
 [3 4 5]]
45
[[5 3 7]
 [4 1 9]
 [2 8 6]]
45
[[2 8 4]
 [6 3 5]
 [1 7 9]]
45


General **Questions**

In [12]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [13]:
data.shape

(5, 3)

In [14]:
#Find the average age of students.
a=data[:,0]
avg=np.mean(a)
print(avg)

18.4


In [23]:
#Extract Math marks of all students.
ar=data[:,1]
ar=ar+5
ar

array([90, 97, 81, 70, 95])

In [24]:
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [16]:
d=data[:,1]+5
d

array([90, 97, 81, 70, 95])

In [17]:
# p=data[:,2]
np.max(data[:,2])
#Find the highest Science mark.

np.int64(95)

In [18]:
# p.max()

#Find the highest Science mark.

In [19]:
data[:,1]>90

array([False,  True, False, False, False])

In [20]:
data[data[:,1]>90]

array([[19, 92, 88]])

Find how many students are younger than 19

In [25]:
data[:,0]<19

array([ True, False,  True,  True, False])

In [27]:
len(data[data[:,0]<19])



3

In [29]:
#calculate the average marks of eaxh subject
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [30]:
#Get data of students that scores atleast 80 in both subjects
data[(data[:,1]>=80)&(data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [31]:
data[:,2][data[:,2]<75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])